package controller;

public enum Command {
	
	LANGUAGE_ES, LANGUAGE_ENG, 
	DATA, MANAGE_DATA, HOME, REPORTS,ADD_CROOP,CREATE_CROOP, CANCEL_ADD, CANCEL_MODIFY,CANCEL_DELETE,
	EXPORT, REPORT_HARV, REPORT_PLANT, REPORT_FILTER, REPORT_COUNT,
	ACCEPT,MODIFY,EDITE_CROOP,DELETE,DELETE_CROOP;

}
